<template>
<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" :width="width" :height="height" viewBox="0 0 32 32" :fill="background">
  <title>check-round</title>
  <path d="M23.926 7.386c0.959-0.959 2.397-0.959 3.355 0s0.959 2.397 
          0 3.355l-12.942 13.661c-0.959 0.959-2.397 0.959-3.355 
          0l-6.231-5.752c-0.959-0.959-0.959-2.397-0.24-3.355s2.397-0.959 
          3.355-0.24l4.314 4.074 11.744-11.744z"></path>
</svg>


</template>

<script>
export default {
  name: 'checkIcon',
  props: ['width', 'height', 'background']
}
</script>

<style>

</style>